baseURL = "http://example.org/"
languageCode = "en-us"
title = "dw-jet's portfolio"
theme = "basic"
Paginate = 5

[params]
  author = "James Teitsworth"
  description = "The fake portfolio of a madman"

  gh_url = "https://api.github.com/users"
  gh_user = "dw-jet"
  
[permalinks]
  posts = "posts/:year/:month/:slug/"
  year = "/posts/:slug/"
  month = "/posts/:slug"

[taxonomies]
  year = "year"
  month = "month"
  tag = "tags"
  category = "categories"

[related]
threshold = 80.0
includeNewer = true
toLower = false
  [[related.indices]]
  name = "keywords"
  weight = 100.0

  [[related.indices]]
  name = "date"
  weight = 10.0