baseURL = "http://example.org/"
languageCode = "en-us"
title = "dw-jet's portfolio"
theme = "basic"

[params]
  author = "James Teitsworth"
  description = "The fake portfolio of a madman"

  gh_url = "https://api.github.com/users"
  gh_user = "dw-jet"
  
[permalinks]
  posts = "posts/:year/:month/:slug/"
  year = "/posts/:slug/"
  month = "/posts/:slug"

[taxonomies]
  year = "year"
  month = "month"
  tag = "tags"
  category = "categories"
  